#开发环境配置
server:
#  服务器的Http端口，默认为8080
  port:  8088
  servlet:
      # 应用的访问路径
        context-path: /
  tomcat:
      # tomcat的URI编码
      uri-encoding: UTF-8
      # tomcat最大线程数，默认为200
      max-threads: 800
      # Tomcat启动初始化的线程数，默认值25
      min-spare-threads: 30

# Spring配置
spring:
  mvc:
#  浏览器静态文件访问路径
    static-path-pattern: /resources/static
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/association?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
#      naming:
#          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # 文件上传
  servlet:
       multipart:
         # 单个文件大小
         max-file-size:  10MB
         # 设置总上传的文件大小
         max-request-size:  20MB

logging:
    root: info
    com.association: debug
    file: log/association-dev.log

thymeleaf:
#将themilef的默认缓存禁用，热加载生效
     cache: false
     prefix:
       classpath: /templates   # 访问template下的html文件需要配置模板，映射

#redis 配置
redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms


# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌秘钥
    secret: abcdefghijklmnopqrstuvwxyz
    # 令牌有效期（默认30分钟）
    expireTime: 30

# MyBatis配置

mybatis:
    # 搜索指定包别名
#    typeAliasesPackage: com.association.project.**.domain
    typeAliasesPackage: com.association.model
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml
